config/routes.rb
Github::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  resources :teams
  resources :off_days

  resources :team_members do
    member do
      get :rescue
    end
  end

  resources :repos do
    collection do
      get :details
    end
  end
  root "repos#index"

  get '/auth/:provider/callback', to: 'sessions#create'

  get 'monitors/lb' => 'monitors#lb'
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  def index
    github.auto_paginate = true
    @orgs = {'AgapeEurope' => [],'CruGlobal' => [], 'PowerToChange' => []}
    @orgs.keys.each do |org_name|
      @orgs[org_name] = github.paginate(github.org(org_name).rels[:repos].href).sort_by { |r| r.name.downcase }
    end
  end

  def details
    @repo_name = params[:name]
    @repo = github.repo(@repo_name)
    @collaborators = @repo.rels[:contributors].get.data.sort_by(&:login)
    @commits = @repo.rels[:commits].get.data
  end
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/repos/_commit.html.erb
<li>
  <strong>Committer</strong> <%= link_to(commit.author.login, "http://github.com/#{commit.author.login}", target: '_blank') if commit.author %><br />
  <%= commit.commit.message %><br />
  <%= link_to('view on github', "http://github.com/#{@repo_name}/commit/#{commit.sha}", target: '_blank') %><br /><br />
</li>

app/views/repos/details.html.erb
<h2><%= link_to(@repo_name, "http://github.com/#{@repo_name}", target: '_blank') %></h2>
<h3>Contributors</h3>
<ul>
<% @collaborators.each do |collaborator| %>
  <li><%= link_to(collaborator.login, "http://github.com/#{collaborator.login}", target: '_blank') %></li>
<% end %>
</ul>
<h3>Recent API Commits (include [api] in commit message)</h3>
<ul>
  <%= render partial: 'commit', collection: @commits.select {|c| c.commit.message.include?('[api]')} %>
</ul>

<h3>Recent Commits</h3>
<ul>
  <%= render partial: 'commit', collection: @commits %>
</ul>

app/views/repos/index.html.erb
<% @orgs.each do |org, repos| %>
  <h2><%= org %></h2>
  <ul>
    <% repos.each do |repo| %>
      <li>
        <%= link_to(repo.name, details_repos_path(name: repo.full_name)) %>
        <%= " - #{repo.description}" if repo.description.present? %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/repos/show.html.erb
<h2><%= link_to(@repo_name, "http://github.com/#{@repo_name}", target: '_blank') %></h2>
<h3>Contributors</h3>
<ul>
<% @collaborators.each do |collaborator| %>
  <li><%= link_to(collaborator.login, "http://github.com/#{collaborator.login}", target: '_blank') %></li>
<% end %>
</ul>
<h3>Recent API Commits (include [api] in commit message)</h3>
<ul>
  <%= render partial: 'commit', collection: @commits.select {|c| c.commit.message.include?('[api]')} %>
</ul>

<h3>Recent Commits</h3>
<ul>
  <%= render partial: 'commit', collection: @commits %>
</ul>