config/routes.rb
Github::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  resources :teams
  resources :off_days

  resources :team_members do
    member do
      get :rescue
    end
  end

  resources :repos do
    collection do
      get :details
    end
  end
  root "repos#index"

  get '/auth/:provider/callback', to: 'sessions#create'

  get 'monitors/lb' => 'monitors#lb'
end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
  belongs_to :team#, inverse_of: :team_members
  has_many :github_commits
  has_many :rescue_time_category_days
  has_many :off_days

  validates :team_id, presence: true

  SOFTWARE_DEV = ['General Software Development', 'Systems Operations', 'Data Modeling & Analysis', 'Quality Assurance',
                  'Project Management', 'Editing & IDEs', 'Design & Planning', 'Troubleshooting', 'General Utilities',
                  'Virtualization']

  WORK_CATS = ['General Business', 'Email', 'Meetings', 'Instant Message', 'Voice Chat', 'Writing',
               'General Communication & Scheduling', 'General Reference & Learning', 'Engineering & Technology',
               'Calendars', 'Administration', 'Operations', 'Gmail', 'Meeting (offline)', 'Customer Relations',
               'General Design & Composition', 'Research', 'Writing']

  def load_data(events = {}, marches = {}, work = {}, team_days = {}, current_token = access_token, start_date, end_date)
    unless events[id]
      # github commits
      begin
        data = github(current_token).user(github_login).rels[:events].get.data
        data.select {|e| e.type == 'PushEvent' && e.created_at > start_date}
            .map {|e|  e.payload.commits.select(&:distinct)
                                        .map {|c| github_commits.where(sha: c.sha, repo: e.repo.name)
                                                                .first_or_create(commit_message: c.message, push_date: e.created_at)
                                             }

                 }
      rescue
        # Don't puke just because github is down
      end
      events[id] = github_commits.where("push_date >= ?", start_date).collect {|c| {date: c.push_date, repo: c.repo, message: c.commit_message, sha: c.sha}}
    end
    # rescue time results for software dev
    begin
      if rescue_time_token.present?
        marches[team_id] ||= {}
        marches[team_id][id] = {}
        work[team_id] ||= {}
        work[team_id][id] = {}
        rows = RescueTime.new(self).data(start_date, end_date).group_by {|r| Date.parse(r[0]) }

        start_date.step(end_date) do |day|
          break if day > Date.today
          # If this is saturday or sunday, count the time towards monday
          acting_day = case
                       when day.saturday?
                         day - 1.day
                       when day.sunday?
                         day + 1.day
                       else
                         day
                       end

          off_day = off_days.find_by(off_day: acting_day)

          coding = 0.0
          work_time = 0.0
          # if acting_day >= Date.yesterday
            # use the data from the API
            if rows && rows[day]
              rows[day].group_by {|r| r[3]}.each do |category, cat_rows|
                cat_total = cat_rows.sum {|r| r[1]}
                day_cat = rescue_time_category_days.where(day: day, category: category).first_or_create
                day_cat.update(amount: cat_total)
                case
                when SOFTWARE_DEV.include?(category)
                  coding += cat_total
                when WORK_CATS.include?(category)
                  work_time += cat_total
                end
              end
            end
          # else
            #use the data in the db
            # coding += rescue_time_category_days.where(day: day, category: SOFTWARE_DEV).sum(:amount)
            # work_time += rescue_time_category_days.where(day: day, category: WORK_CATS).sum(:amount)
          # end

          coding_amount = ((coding / 3600) * 10).to_i / 10.0
          work_amount = ((work_time / 3600) * 10).to_i / 10.0
          if work_amount + coding_amount > 0.2
            work[team_id][id][acting_day] ||= 0
            work[team_id][id][acting_day] += work_amount + coding_amount
            unless off_day
              marches[team_id][id][acting_day] ||= 0
              marches[team_id][id][acting_day] += coding_amount
              team_days[team_id] ||= {}
              team_days[team_id][acting_day] ||= 0
              team_days[team_id][acting_day] += coding_amount unless leader?
            end
          end
        end
      end
    #rescue
      # Unable to pull data for this person from rescue time
    end
  end

  def github(current_token)
    token = access_token || current_token

    Octokit::Client.new :access_token => token
  end
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_filter :get_team_member

  def rescue
    @date = params[:start_date] ? Date.parse(params[:start_date]) : Date.today

    if current_user.leader?
      @rows = RescueTime.new(@team_member).data(@date, @date)
      @details = RescueTime.new(@team_member).detail(@date, @date)
    end
  end

  def index
    @teams = Team.all

    @start_date = params[:start_date] ? Date.parse(params[:start_date]) : Date.today.beginning_of_year
    @end_date = Date.yesterday


    expiration_time = 1.day
    
    @off_days = Rails.cache.fetch(['off_days', @start_date], expires_in: expiration_time) do
      counts = {}
      TeamMember.all.each do |tm|
        counts[tm.id] = tm.off_days.group(:reason).count
      end
      counts
    end
    
    @member_summary = Rails.cache.fetch(['member_summary', @start_date])
    @commit_summary = GithubCommit.group(:team_member_id).order("count(*) desc").count

    unless @member_summary
      @events = {}
      @marches = {}
      @work = {}
      @team_days = {}

      token = TeamMember.where("access_token is not null").first.access_token

      @teams.each do |team|
        team.load_data(@events, @marches, @work, @team_days, token, @start_date, @end_date)
      end

      @member_marches = {}
      Team.all.each do |team|
        @member_marches.merge!(@marches[team.id])
      end

      @member_summary = {}
      @member_marches.each do |id, marches|
        @member_summary[id] = marches.keys.length > 0 ? marches.sum { |date, amount| amount } / marches.keys.length : 0
      end

      Rails.cache.write(['member_summary', @start_date], @member_summary, expires_in: expiration_time)
    end

    @member_summary = Hash[@member_summary.sort_by { |id, amount| amount }.reverse]
  end

  private

  def get_team_member
    @team_member = TeamMember.find(params[:id]) if params[:id]
  end
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/views/team_members/_rescue.html.erb
<h2><%= @team_member.name %> - <%= @date.to_s(:long) %></h2>
<%= link_to('previous day', rescue_team_member_path(@team_member, start_date: @date - 1.day), remote: true) %>
<% if @date < Date.today %> |
  <%= link_to('next day', rescue_team_member_path(@team_member, start_date: @date + 1.day), remote: true) %>
<% end %>
  <br /><br />
<% if off_day = @team_member.off_days.find_by(off_day: @date) %>
  <%= link_to("Unmark as #{off_day.reason}", off_day_path(off_day), method: :delete) %>
<% else %>
  Mark as:
  <% %w[sick vacation holiday mpd admin].each do |reason| %>
    <%= link_to(reason, off_days_path(team_member_id: @team_member.id, off_day: @date, reason: reason), method: :post) %>
  <% end %>
<% end %>
<% if current_user.leader? %>
  <br/>
  <a class="toggle_view" data-id="<%= @team_member.id %>" href="#">Toggle details</a>
  <div id="categories_<%= @team_member.id %>">
    <table border="0" cellpadding="5">
      <tr>
        <th>Time Spent</th>
        <th>Thing</th>
      </tr>
      <tbody>
      <% @rows.select { |row| row[1] >= 5.minutes }.each do |row| %>
        <tr>
          <td><%= distance_of_time_in_words(row[1]) %></td>
          <td><%= row[3] %></td>
        </tr>
      <% end %>
      </tbody>
      <tfoot style="border: 1px solid black; background: #f0f0f0">
      <% cat_rows = @rows.select { |row| row[1] < 5.minutes }
        .group_by { |row| row[4] }
        .collect { |cat, cat_rows| [cat, cat_rows.sum {|r| r[1].to_i}] }
        .select { |c| c[1] >= 5.minutes }
        .sort_by {|c| c[1]}
        .reverse %>
      <% cat_rows.each do |c| %>
        <tr>
          <td><%= distance_of_time_in_words(c[1]) %></td>
          <td>misc</td>
        </tr>
      <% end %>
      </tfoot>

    </table>
  </div>
  <div id="detail_<%= @team_member.id %>" style="display:none">
    <table border="0" cellpadding="5">
      <tr>
        <th>Time Spent</th>
        <th>Thing</th>
        <th>Category</th>
      </tr>
      <tbody>
      <% @details.select { |row| row[1] >= 5.minutes }.each do |row| %>
        <tr>
          <td><%= distance_of_time_in_words(row[1]) %></td>
          <td><%= row[3] %></td>
          <td><%= row[4] %></td>
        </tr>
      <% end %>
      </tbody>
      <tfoot style="border: 1px solid black; background: #f0f0f0">
      <% cat_rows = @details.select { |row| row[1] < 5.minutes }
        .group_by { |row| row[4] }
        .collect { |cat, cat_rows| [cat, cat_rows.sum {|r| r[1].to_i}] }
        .select { |c| c[1] >= 5.minutes }
        .sort_by {|c| c[1]}
        .reverse %>
      <% cat_rows.each do |c| %>
        <tr>
          <td><%= distance_of_time_in_words(c[1]) %></td>
          <td>misc</td>
          <td><%= c[0] %></td>
        </tr>
      <% end %>
      </tfoot>

    </table>
  </div>

<% end %>

app/views/team_members/index.html.erb
<h2><%= Time.now.year %> YTD</h2>
<style>
table {
  border-collapse: collapse;
  margin: 10px;
}

table, th, td {
  border: 1px solid black;
  padding: 10px;
}
</style>

<table>
  <tr>
    <th>Name</th>
    <th><%= link_to('Hours', team_members_path(sort: 'hours')) %></th>
    <th><%= link_to('Commits', team_members_path(sort: 'commits')) %></th>
    <th>Admin</th>
    <th>Sick</th>
    <th>Vacation</th>
  </tr>
  <% collection = params[:sort] == 'commits' ? @commit_summary : @member_summary %>
  <% collection.each do |id, amount| %>
    <% team_member = TeamMember.find(id) %>
    <% next unless @off_days[team_member.id] %>
    <tr style="border:1px solid black; margin:10px; padding: 10px">
      <td>
        <%= team_member.name %>
      </td>
      <td>
        <% if @member_summary[team_member.id] %>
          <i class="fa fa-circle" style="color:<%= amount_to_color(@member_summary[team_member.id]) %>"></i> <%= round(@member_summary[team_member.id], 2) %>
        <% end %>
      </td>
      <td>
        <%= number_with_delimiter(@commit_summary[team_member.id]) %>
      </td>
      <td>
        <%= @off_days[team_member.id]['admin'] %>
      </td>
      <td>
        <%= @off_days[team_member.id]['sick'] %>
      </td>
      <td>
        <%= @off_days[team_member.id]['vacation'] %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to('Back to dashboard', teams_path) %>

app/views/team_members/rescue.js.erb
$('#js-rescue_details_<%= @team_member.github_login %>').html('<%= j(render('rescue')) %>')
$('#js-rescue_details_<%= @team_member.github_login %>').dialog({width: 'auto'})